### ISSUE TITLE
brew install android-sdk fails with Linuxbrew

### ISSUE THREAD

**Issue by zedtux** [NovatecConsulting/fastlane-plugin-android_sdk_update#5]
When this plugin needs to install the Android SDK, it uses [the command line `cask ls --versions android-sdk || brew cask install android-sdk `](https://github.com/NovaTecConsulting/fastlane-plugin-android_sdk_update/blob/31698c76c661dc92717d63f6c54915a4c08843cd/lib/fastlane/plugin/android_sdk_update/actions/android_sdk_update_action.rb#L12) which doesn't work with Linuxbrew because of the following:

```
Error: No available formula with the name "android-sdk"
It was migrated from homebrew/core to homebrew/cask.
You can access it again by running:
  brew tap homebrew/cask
And then you can install it by running:
  brew cask install android-sdk
```

**Comment by zedtux** [comment]
Oh ... 

```
Error: Homebrew Cask is only supported on macOS
```

So actually this plugin is macOS only compatible?

**Comment by zedtux** [comment]
Okay so looking further the code I had the confirmation you're supporting only macOS 🤦‍♂️.

Do you have any plan to support Linux? (Running Android on Linux is quite common)

**Comment by m-ruhl** [comment]
The plugin did support Linux.

A few months ago, the package was removed from Linuxbrew, so we need to refactor the plugin.

**Comment by zedtux** [comment]
Well, If I'm not mistaking, [this isn't the case](https://github.com/NovaTecConsulting/fastlane-plugin-android_sdk_update/blob/master/lib/fastlane/plugin/android_sdk_update/actions/android_sdk_update_action.rb#L10-L16).

```ruby
        if FastlaneCore::Helper.mac?
          require 'fastlane/plugin/brew'
          Actions::BrewAction.run(command: "cask ls --versions android-sdk || brew cask install android-sdk")
          sdk_path = File.realpath("../../..", FastlaneCore::CommandExecutor.which("sdkmanager"))
        else
          UI.user_error! 'Your OS is currently not supported.'
        end
```

**Comment by m-ruhl** [comment]
Not anymore, I removed the support last week: 31698c76c661dc92717d63f6c54915a4c08843cd
I didn't release it, not to break it for current Linux users.

Long story short, we are still planning to support Linux again

**Comment by m-ruhl** [comment]
With version 1.0.0, we added linux support again :)

**Comment by zedtux** [comment]
Thank you @m-ruhl
