### ISSUE TITLE
Not working anymore as brew cask cannot be used

### ISSUE THREAD

**Issue by sneps85** [NovatecConsulting/fastlane-plugin-android_sdk_update#7]
Hi,
the command "brew cask [action]" was deprecated for a while and was now removed. It is considered to to replace it with "brew [action] --cask".

As your plugin uses both, "brew cask ls" and "brew cask install", I made a pull request for you, which just replaces it with "brew list --cask" and "brew install --cask".

Please accept my pull request or fix the issue by yourself, so that your great plugin is usable again. If someone needs it immediately, feel free to use the url of my fork in your fastlane Pluginfile.

Thank you

**Comment by m-ruhl** [comment]
Hi @sneps85,

Thanks for the pull request.. I integrated it and published a new version 👍
