### ISSUE TITLE
Use Android cmdline-tools

### ISSUE THREAD

**Issue by cleemansen** [NovatecConsulting/fastlane-plugin-android_sdk_update#8]
Are there any plans to switch to the newer [Android cmdline-tools](https://developer.android.com/studio#cmdline-tools)?

Currently the now deprecated [SDK Tools](https://developer.android.com/studio/releases/sdk-tools) are in use.

**Comment by m-ruhl** [comment]
Hi @cleemansen,

Yes, it is planned, but I'm still having some troubles with the migration

**Comment by m-ruhl** [comment]
Done with the newest release `2.0.0`
