### ISSUE TITLE
Make it compatible with Java 11

### ISSUE THREAD

**Issue by sneps85** [NovatecConsulting/fastlane-plugin-android_sdk_update#9]
As gradle 7.x requires Java 11, please make your plugin work with it. Currently, the following exception is thrown using Java 11:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema

**Comment by samsonpaul87** [comment]
Is there any update on this issue? I am also getting this exception and waiting for an update.

**Comment by m-ruhl** [comment]
I don't think the issue is within the plugin itself.

The plugin uses the [`sdkmanager`](https://developer.android.com/studio/command-line/sdkmanager) from android platform tools, and to my knowledge this tools is still only compatible with Java 8.

**Comment by samsonpaul87** [comment]
Please see the screenshot attached. Looking through the logs, one can clearly see that the issue is triggering from withing the plugin itself.
![image](https://user-images.githubusercontent.com/21302132/146759909-f068775c-fdb4-42bc-a180-85d9df3d4ab3.png)

**Comment by m-ruhl** [comment]
Yes, but the plugin is written in Ruby and you see a Java-Stacktrace error from the `sdkmanager`

I currently don't see a way to fix it, because the problem is in the `sdkmanager` from Google.. or please correct me if you find a solution/workaround.

**Comment by samsonpaul87** [comment]
Ahh okay. I got it now. Thank you @m-ruhl for correcting me. 
So, the problem lies in the sdkmanager and not in this fastlane plugin. I will dig more into there and see if I can figure it out.

**Comment by sneps85** [comment]
yes, the problem is unfortunately part of the sdkmanager; you can close the issue, as not resolvable

**Comment by andrii-ts** [comment]
Any updates for that issue? I have the same issue

**Comment by m-ruhl** [comment]
@andrii-ts 

It should be supported with the latest version `2.0.0` of the plugin and `android-commandlinetools`

> Use android-commandlinetools instead of deprecated android-sdk
> To uninstall existing sdk: brew uninstall --cask android-sdk
